name: snow-drought-modeling
channels:
- conda-forge
- defaults

dependencies:
- python=#check version!
- os
- pathlib
- pandas
- geopandas
- xarray
- rioxarray
- holoviews
- hvplot
- requests
- time
- tqdm
- pygeohydro
- pyarrow
- matplotlib
- shapely
- scikit-learn

# Use pip to install src folder
- pip
- pip:
  - -e