name: snow-drought-modeling
channels:
- conda-forge
- defaults

dependencies:
- python=#check version!
- os
- pathlib
- pandas
- geopandas
- xarray
- rioxarray
- holoviews
- hvplot
- matplotlib
- requests
- time
- tqdm
- pygeohydro
- pyarrow
- shapely
- sklearn
- xgboost

# Use pip to install src folder
- pip
- pip:
  - -e