name: snow-drought-modeling
channels:
- conda-forge
- defaults

dependencies:
- python=#check version!
- datetime
- earthaccess
- geopandas
- holoviews
- hvplot
- matplotlib
- math
- numpy
- os
- pathlib
- pandas
- panel
- pickle
- pygeohydro
- pyarrow
- rasterio
- requests
- rioxarray
- shapely
- sklearn
- sys
- time
- tqdm
- xarray
- zipfile

# Use pip to install src folder
- pip
- pip:
  - -e